version: 1
builder:
  configs:
  - platform: ios
    documentation_targets: [AppleSwiftProtobuf]
    scheme: AppleSwiftProtobuf
  - platform: tvos
    scheme: AppleSwiftProtobuf
  - platform: watchos
    scheme: AppleSwiftProtobuf
